# Generated by Django 4.0 on 2023-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='', upload_to='Image_users', verbose_name='รูปโปรไฟล์'),
        ),
    ]
