# Generated by Django 4.0 on 2023-11-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
