# Generated by Django 4.0 on 2023-11-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.AddField(
            model_name='myuser',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
