# Generated by Django 4.0 on 2023-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='perfix',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10, null=True, verbose_name='คำนำหน้า'),
        ),
    ]
