# Generated by Django 3.2 on 2024-01-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={'ordering': ['-id'], 'verbose_name_plural': 'กลุ่มงาน'},
        ),
        migrations.AddField(
            model_name='profile',
            name='workgroup',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workgroup', verbose_name='กลุ่มงาน'),
        ),
    ]
