# Generated by Django 3.2 on 2024-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Image_users', verbose_name='รูปโปรไฟล์'),
        ),
    ]
