# Generated by Django 4.0 on 2023-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='ราคา'),
        ),
    ]
