# Generated by Django 4.0 on 2023-11-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
