# Generated by Django 4.0 on 2023-10-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_date_receive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='return_status',
            new_name='refuse',
        ),
    ]
