# Generated by Django 4.0 on 2023-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_refuse_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_receive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับของ'),
        ),
    ]
