# Generated by Django 4.0 on 2023-11-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
